---
# tasks file for 02-loadbalancer

- name: Install haproxy
  yum:
    name:
      - podman
    state: present

- name: Install OpenShift 4 Loadbalancer SystemD service
  template:
    src: loadbalancer.service.j2
    dest: "/etc/systemd/system/loadbalancer.service"
    mode: 0644

- name: Enable and start loadbalancer.service
  systemd:
    name: "loadbalancer.service"
    daemon_reload: yes
    enabled: yes
    state: started

- name: Collect services facts
  service_facts:
  register: services_state

- name: Check loadbalancer.service
  fail:
    msg: "Load balancer service loadbalancer.service is not running!!! Please check, run: systemctl status loadbalancer.service"
  when: services_state.ansible_facts.services[ 'loadbalancer.service'].state != 'running'    
