apiVersion: v1
baseDomain: filice.eu
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: 3
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: 3
metadata:
  creationTimestamp: null
  name: ocp4
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 192.168.126.0/24
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  libvirt:
    URI: qemu+tcp://192.168.122.1/system
    network:
      if: tt0
publish: External
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfM2M5YzNmMjI1YzVhNDA3NDljOTlmYmM0NWFkYWZlYmE6VVVIVDRRMlZFSlJRSTkzSk04R0xHUFJQTDFMVlBLQTBIME9OUEJNSTNFVEpGNUMxWDA3WEpaM1BLWktPVDFRTg==","email":"afilice@redhat.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfM2M5YzNmMjI1YzVhNDA3NDljOTlmYmM0NWFkYWZlYmE6VVVIVDRRMlZFSlJRSTkzSk04R0xHUFJQTDFMVlBLQTBIME9OUEJNSTNFVEpGNUMxWDA3WEpaM1BLWktPVDFRTg==","email":"afilice@redhat.com"},"registry.connect.redhat.com":{"auth":"fHVoYy1wb29sLTNmMzYwMmZiLTY0MjYtNDUzNi05MjhiLTc4ZGRhMWJkMzMzMDpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSXdaamhpTldKbE0ySm1aakEwTkRjME9USTNObVl5TlRSbU1HWXlZMkk1WmlKOS5oWm9Vd0tiM3FvMWNreGlkTVhuTzdnMWZxVERvZElzcm1pUHYyc0pMM3V0TDRzN3ItdU5ObTlWYUhIV0s1cXZ3THRIbnVIQkhFcG9jOG12SmxNbVB6N1FjUEJoeUktWnU4dmZBc2ZuaWE3SlVVdWFXeWE2X09IZ0VFT2JfSmlJQ2NuWHVfM2d3SFpueHMwUWxrTUNBaEJnRDU5U3JSc3pPd0hrMTJjSkx2c2Y0dFhuMDhadWVObjE4Vl9FOFczZ2lZcXZEZldzZ0c2MXdCbzY0TnFpVXF5eDRIUXFnVHFZMkJzWFVweWgzYTJjTVNfcGVOOFVoZmVkdkNta0hVTEV4SWVQWTV0OWlRaklSVDZleFNjWV9UMi1mdFZSQjZlcHRaaTFWYkNUSGVLbDFndWk0NHBvbkxMeVVONUs0Z2FzT1E5V3BGcWtIRDdyb1oycXZGVkkzTkgybnVRdUJpTjA4ekxvTUZIbXB0dEFHUmoyT3BQelBRZ0xyRzBTNW9YRVVCRHRiMGlMT3VKTkpYZzAwUzNkOTRMNzczWGxOaDAyTE9sQU1JaXJGbGJrbzd3TC1KdHRXRlJoejkySllzY1dZV3JWUUFsekY2ZzRMNVVZRzVyeE9nTVlNZFV5UDQzREJQZ3ZGZVRZWUl1QnUxMzU2UkJ2TXhyT01nc2w5Z1M3YnAzVkdTNVBjOXI1M2dpWHBQTVBQdEs4bXhUR1ZQUlNxODJ3elBxVGRKWG5hQ2VvR1NYQ1pNbFA5TEVDT3NDRXBFZGltQ0NnNVdTaVl3eDVWblF1cFlobFRsQzlXNTZSQ1lsY0pWczZDT0szU2tIOGF5TDdOdUFraEotYjN2SG5INU50bjlvN3I4Uy0zRjI3VS1xbF9LMGYtdUFrWlNwZnZiVldiUW4ydy1PRQ==","email":"afilice@redhat.com"},"registry.redhat.io":{"auth":"fHVoYy1wb29sLTNmMzYwMmZiLTY0MjYtNDUzNi05MjhiLTc4ZGRhMWJkMzMzMDpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSXdaamhpTldKbE0ySm1aakEwTkRjME9USTNObVl5TlRSbU1HWXlZMkk1WmlKOS5oWm9Vd0tiM3FvMWNreGlkTVhuTzdnMWZxVERvZElzcm1pUHYyc0pMM3V0TDRzN3ItdU5ObTlWYUhIV0s1cXZ3THRIbnVIQkhFcG9jOG12SmxNbVB6N1FjUEJoeUktWnU4dmZBc2ZuaWE3SlVVdWFXeWE2X09IZ0VFT2JfSmlJQ2NuWHVfM2d3SFpueHMwUWxrTUNBaEJnRDU5U3JSc3pPd0hrMTJjSkx2c2Y0dFhuMDhadWVObjE4Vl9FOFczZ2lZcXZEZldzZ0c2MXdCbzY0TnFpVXF5eDRIUXFnVHFZMkJzWFVweWgzYTJjTVNfcGVOOFVoZmVkdkNta0hVTEV4SWVQWTV0OWlRaklSVDZleFNjWV9UMi1mdFZSQjZlcHRaaTFWYkNUSGVLbDFndWk0NHBvbkxMeVVONUs0Z2FzT1E5V3BGcWtIRDdyb1oycXZGVkkzTkgybnVRdUJpTjA4ekxvTUZIbXB0dEFHUmoyT3BQelBRZ0xyRzBTNW9YRVVCRHRiMGlMT3VKTkpYZzAwUzNkOTRMNzczWGxOaDAyTE9sQU1JaXJGbGJrbzd3TC1KdHRXRlJoejkySllzY1dZV3JWUUFsekY2ZzRMNVVZRzVyeE9nTVlNZFV5UDQzREJQZ3ZGZVRZWUl1QnUxMzU2UkJ2TXhyT01nc2w5Z1M3YnAzVkdTNVBjOXI1M2dpWHBQTVBQdEs4bXhUR1ZQUlNxODJ3elBxVGRKWG5hQ2VvR1NYQ1pNbFA5TEVDT3NDRXBFZGltQ0NnNVdTaVl3eDVWblF1cFlobFRsQzlXNTZSQ1lsY0pWczZDT0szU2tIOGF5TDdOdUFraEotYjN2SG5INU50bjlvN3I4Uy0zRjI3VS1xbF9LMGYtdUFrWlNwZnZiVldiUW4ydy1PRQ==","email":"afilice@redhat.com"}}}'
sshKey: |
 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDJOuATbYagGYRk7wUVwGI3JWpjrQj8R/XCXD9aGi6h4lJ4Feq2sTqNHer83sDf5G+SV/9yuUmWAdFSBroBGcpDoraaZIjW6GmgSj4OFxz1aSoyJu1I5U4ZkUT69cHVg1KjjYTDs94q38VRq86l1aoesNugTNrH2U7JuR7rk/lnQ2QfCrD7ZRHtpa0xdfZqS1BL4PD2hZLqOlajiJKwXnK3PWMCEvT0jHy0dPiVgFmW6c0DYW/yWolY1eGHD4GT/OSbXjb22J520tbGfLwwRD8rKteb4c3BhUlkQSsjeaCSznmP7+Q9zgu+8amBTCsUYjI8sNHKXS4145RKLEgcUxfVyc/caY6hfMYsOhllZTqtc/XJD33VqeZbDl4Z1TteO68wz+ystqRqnguPgJHeEM5QzDm/zd8tKya8JI8Vx/xr5TTYI06W+g4YKInAwx0C2+dV9lprlEtlTdd0IpFPtWiNHic9HaCSdL4x1uNBOWFKVIb9ENxP1n0nmhIhn7bewkU= root@m5759.contaboserver.net 
