---
- name: Libvirt IPI Openshift 4
  hosts: localhost

  vars:
    kvm_workdir: "{{ ansible_env.HOME }}"
    kvm_nestedvirtualization: true
    kvm_pool_location: "/var/lib/libvirt/openshift-images"
    nfs_export_path: "var/lib/libvirt/openshift-nfs"    
    ocp_install_file_path: "install-config.yaml"
    ocp_release: "4.11.0"
    ocp_master_memory: 16
    ocp_master_cpu: 4
    ocp_master_disk: 150
    ocp_worker_memory: 20
    ocp_worker_cpu: 4
    ocp_worker_disk: 150

  roles:
    - {role: '01-prepare-host.yml'}
    - {role: '02-loadbalancer'}
    - {role: '03-build-openshift-installer'}
    - {role: '04-cluster-install'}