- include_vars: "{{ ocp_install_file_path }}"

- name: Create certificates dir
  ansible.builtin.file:
    path: "{{ ocp_install_path }}/install/certificate/{{ metadata.name }}.{{ baseDomain }}"
    state: directory
    mode: 0755

- name: Create account-key
  community.crypto.openssl_privatekey:
    path: "{{ ocp_install_path }}/install/certificate/account.key"
    type: RSA
    size: 4096

- name: Fetch letsencrypt root ca
  ansible.builtin.get_url:
    url: https://letsencrypt.org/certs/isrgrootx1.pem.txt
    dest: "{{ ocp_install_path }}/install/certificate/isrgrootx1.pem"

- name: Create {{ metadata.name }}.{{ baseDomain }}.key
  community.crypto.openssl_privatekey:
    path: "{{ ocp_install_path }}/install/certificate/{{ metadata.name }}.{{ baseDomain }}/cert.key"
    type: RSA
    size: 4096

- name: Generate an OpenSSL Certificate Signing Request with subjectAltName extension
  community.crypto.openssl_csr:
    path: "{{ ocp_install_path }}/install/certificate/{{ metadata.name }}.{{ baseDomain }}/cert.csr"
    privatekey_path: "{{ ocp_install_path }}/install/certificate/{{ metadata.name }}.{{ baseDomain }}/cert.key"
    subject_alt_name: "DNS:*.apps.{{ metadata.name }}.{{ baseDomain }},DNS:api.{{ metadata.name }}.{{ baseDomain }}"

- name: Create a challenge for {{ metadata.name }}.{{ baseDomain }} using a account key file.
  community.crypto.acme_certificate:
    account_key_src: "{{ ocp_install_path }}/install/certificate/account.key"
    account_email: "{{ letsencrypt_account_email }}"
    src: "{{ ocp_install_path }}/install/certificate/{{ metadata.name }}.{{ baseDomain }}/cert.csr"
    cert: "{{ ocp_install_path }}/install/certificate/{{ metadata.name }}.{{ baseDomain }}/cert.crt"
    challenge: dns-01
    acme_directory: "https://acme-v02.api.letsencrypt.org/directory"
    acme_version: 2
    # Renew if the certificate is at least 30 days old
    remaining_days: 60
    terms_agreed: yes
  register: sample_com_challenge

- name: Debug var only with -vv
  ansible.builtin.debug:
    var: sample_com_challenge
    verbosity: 2

- name: Set challenge_data_dns
  ansible.builtin.set_fact:  # noqa no-handler
    challenge_data_dns: "{{ sample_com_challenge.challenge_data_dns }}"
  when: sample_com_challenge is changed

- name: Create DNS record at CloudFlare
  delegate_to: localhost
  community.general.net_tools.cloudflare_dns:
    zone: "{{ baseDomain }}"
    record: "{{ item.0.key }}"
    # 1 for automatic
    ttl: 1
    type: TXT
    value: "{{ item.1 }}"
    account_email: "{{ cloudflare_account_email }}"
    account_api_token: "{{ cloudflare_account_api_token }}"
  register: record
  loop: "{{ challenge_data_dns | default({}) | dict2items | subelements('value') }}"
  when: (cloudflare_account_email is defined) and sample_com_challenge is changed    

- name: DNS record info
  ansible.builtin.debug:    # noqa no-handler
    msg: "{{ item.0.key }} TXT {{ item.1 }}"
  loop: "{{ challenge_data_dns | default({}) | dict2items | subelements('value') }}"
  when: sample_com_challenge is changed

- name: Wait for DNS changes
  ansible.builtin.pause:   # noqa no-handler
    seconds: 40
  when: sample_com_challenge is changed

- name: Let the challenge be validated and retrieve the cert and intermediate certificate
  community.crypto.acme_certificate:  # noqa no-handler
    account_key_src: "{{ ocp_install_path }}/install/certificate/account.key"
    account_email: "{{ letsencrypt_account_email }}"
    src: "{{ ocp_install_path }}/install/certificate/{{ metadata.name }}.{{ baseDomain }}/cert.csr"
    cert: "{{ ocp_install_path }}/install/certificate/{{ metadata.name }}.{{ baseDomain }}/cert.crt"
    fullchain: "{{ ocp_install_path }}/install/certificate/{{ metadata.name }}.{{ baseDomain }}/fullchain.crt"
    chain: "{{ ocp_install_path }}/install/certificate/{{ metadata.name }}.{{ baseDomain }}/intermediate.crt"
    challenge: dns-01
    acme_version: 2
    acme_directory: "https://acme-v02.api.letsencrypt.org/directory"
    remaining_days: 60
    data: "{{ sample_com_challenge }}"
  when: sample_com_challenge is changed

- name: Delete DNS record at CloudFlare
  delegate_to: localhost
  community.general.net_tools.cloudflare_dns:
    zone: "{{ baseDomain }}"
    record: "{{ item.0.key }}"
    # 1 for automatic
    ttl: 1
    type: TXT
    value: "{{ item.1 }}"
    account_email: "{{ cloudflare_account_email }}"
    account_api_token: "{{ cloudflare_account_api_token }}"
    state: absent
  loop: "{{ challenge_data_dns | default({}) | dict2items | subelements('value') }}"
  when: (cloudflare_account_email is defined) and sample_com_challenge is changed

- name: concat root ca and intermediate
  ansible.builtin.shell: "cat {{ ocp_install_path }}/install/certificate/isrgrootx1.pem {{ ocp_install_path }}/install/certificate/{{ metadata.name }}.{{ baseDomain }}/intermediate.crt >> {{ ocp_install_path }}/install/certificate/{{ metadata.name }}.{{ baseDomain }}/ca-bundle.pem"   # noqa line-length
  args:
    creates: "{{ ocp_install_path }}/install/certificate/{{ metadata.name }}.{{ baseDomain }}/ca-bundle.pem"  

